// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fizzbuzz.sql

package db

import (
	"context"
)

const getTopFizzBuzzStat = `-- name: GetTopFizzBuzzStat :one
SELECT int1, int2, "limit", str1, str2, hits
FROM fizzbuzz_stats
ORDER BY hits DESC
LIMIT 1
`

type GetTopFizzBuzzStatRow struct {
	Int1  int32
	Int2  int32
	Limit int32
	Str1  string
	Str2  string
	Hits  int64
}

func (q *Queries) GetTopFizzBuzzStat(ctx context.Context) (GetTopFizzBuzzStatRow, error) {
	row := q.db.QueryRowContext(ctx, getTopFizzBuzzStat)
	var i GetTopFizzBuzzStatRow
	err := row.Scan(
		&i.Int1,
		&i.Int2,
		&i.Limit,
		&i.Str1,
		&i.Str2,
		&i.Hits,
	)
	return i, err
}

const upsertFizzBuzzStat = `-- name: UpsertFizzBuzzStat :exec
INSERT INTO fizzbuzz_stats (int1, int2, "limit", str1, str2, hits)
VALUES ($1, $2, $3, $4, $5, 1)
ON CONFLICT (int1, int2, "limit", str1, str2)
DO UPDATE SET
    hits       = fizzbuzz_stats.hits + 1,
    updated_at = NOW()
`

type UpsertFizzBuzzStatParams struct {
	Int1  int32
	Int2  int32
	Limit int32
	Str1  string
	Str2  string
}

func (q *Queries) UpsertFizzBuzzStat(ctx context.Context, arg UpsertFizzBuzzStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertFizzBuzzStat,
		arg.Int1,
		arg.Int2,
		arg.Limit,
		arg.Str1,
		arg.Str2,
	)
	return err
}
