// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type FizzbuzzStat struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Int1      int32
	Int2      int32
	Limit     int32
	Str1      string
	Str2      string
	Hits      int64
}
